import Link from "next/link";
import { notFound } from "next/navigation";
import { loadSubmissionWithEntries } from "@/lib/actions/tally";
import { supabaseConfigured } from "@/lib/supabase/configured";
import PrintButton from "./PrintButton";
import SetupNotice from "../../SetupNotice";

export const dynamic = "force-dynamic";

export default async function ExportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!supabaseConfigured()) return <SetupNotice />;
  const { submission, entries } = await loadSubmissionWithEntries(id);
  if (!submission) notFound();

  const filled = entries.filter((e) => e.extracted_value && e.review_status !== "missing").length;

  return (
    <main className="mx-auto max-w-3xl px-6 py-10 print:max-w-none print:px-0 print:py-0">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <Link href={`/tally/${id}`} className="text-sm text-neutral-500 hover:text-neutral-900">
          ← Back to submission
        </Link>
        <PrintButton />
      </div>

      <header className="mb-8 border-b-2 border-neutral-900 pb-4">
        <h1 className="text-2xl font-bold text-neutral-900">Mortgage Loan Application — Filled Template</h1>
        <div className="mt-3 grid grid-cols-2 gap-x-8 gap-y-1 text-sm text-neutral-700">
          <p><span className="font-semibold">Client:</span> {submission.client_name ?? "—"}</p>
          <p><span className="font-semibold">Status:</span> {submission.status}</p>
          <p><span className="font-semibold">Agent:</span> {submission.agent_name ?? "—"}{submission.agent_agency ? ` (${submission.agent_agency})` : ""}</p>
          <p><span className="font-semibold">Completeness:</span> {Math.round(Number(submission.completeness_score))}% ({filled}/{entries.length} fields)</p>
          <p><span className="font-semibold">Source:</span> {submission.source_format ?? "—"}</p>
          <p><span className="font-semibold">Date:</span> {new Date(submission.created_at).toLocaleDateString("en-MY", { dateStyle: "long" })}</p>
        </div>
      </header>

      <table className="w-full border-collapse text-sm">
        <tbody>
          {entries.map((entry) => {
            const missing = !entry.extracted_value || entry.review_status === "missing";
            return (
              <tr key={entry.id} className="border-b border-neutral-200">
                <td className="w-2/5 py-2.5 pr-4 align-top font-medium text-neutral-700">
                  {entry.template_fields?.field_label}
                  {entry.template_fields?.is_required && <span className="text-red-500"> *</span>}
                </td>
                <td className="py-2.5 align-top">
                  {missing ? (
                    <span className="font-semibold text-red-600">☐ MISSING — to obtain</span>
                  ) : (
                    <span className="text-neutral-900">{entry.extracted_value}</span>
                  )}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <footer className="mt-10 text-xs text-neutral-400 print:mt-16">
        Generated by Client Info Tally · {new Date().toLocaleString("en-MY")} · * required field
      </footer>
    </main>
  );
}
